server:
  port: 8001

spring:
  application:
    name: yjjeong-service
  devtools:
    livereload:
      enabled: false # livereload 사용시 활성화
    restart:
      enabled: false #운영 에서는 제거.
# logging:
#   config: classpath:log4j2.xml
eureka:
  instance:
    hostname: localhost
    instance_id: ${spring.application.name}-${server.port}:${spring.application.instance_id:${random.value}}
  client:
    # 나자신은 등록하지 않음
    register-with-eureka: true
    # 마이크로 서비스 인스턴스 목록을 로컬에 캐시할 것인지의 여부
    fetch-registry: true
    ## 아래 설정이 없으면 다음 에러
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, shutdown
  endpoint:
    shutdown:
      enabled: true
